export const SEARCH_ACTIONS = {
    SEARCH_LOADING: "SEARCH_LOADING",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",
    NEW_USER_SEARCH: "NEW_USER_SEARCH"
};

export const RESULTS_ACTIONS = {
    RESULTS_LOADING: "RESULTS_LOADING",
    RESULTS_SUCCESS: "RESULTS_SUCCESS",
    RESULTS_FAILURE: "RESULTS_FAILURE"
};
